networks:
  grafana: 

services:
  application:
    build: 
      context: .
      args:
        - http_proxy
        - https_proxy
        - number_of_build_jobs=12
      network: host
    ports:
      - 8080:8080
    networks:
      - grafana
  prometheus:
    build: 
      context: ./prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - grafana
  grafana:
    build:
      context: ./grafana
    ports:
      - 3000:3000
    networks:
      - grafana
