services:
  application:
    build: 
      context: .
      args:
        - http_proxy
        - https_proxy
        - number_of_build_jobs=12
      network: host
  prometheus:
    build: 
      context: ./prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
