networks:
  grafana: 

services:
  application:
    build: 
      context: .
      args:
        - http_proxy
        - https_proxy
        - number_of_build_jobs=12
      network: host
    ports:
      - 8080:8080
    networks:
      - grafana
  prometheus:
    build: 
      context: ./prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - grafana
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/home.json"
    ports:
      - 3000:3000
    volumes:
      - "./grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/"
    networks:
      - grafana
